package com.livsdesign.bluetooth.page.connection

class BluetoothUuids {
    companion object {

        const val SERVICE_OTA = "00002600-0000-1000-8000-00805f9b34fb"

        //应该具备indicate和write
        const val CHARACTERISTIC_CTRL = "00007000-0000-1000-8000-00805f9b34fb"

        //应当具备READ，WRITE NO RESPONSE
        const val CHARACTERISTIC_DATA = "00007001-0000-1000-8000-00805f9b34fb"

        const val SERVICE_BX_DEBUG = "00006666-d102-e111-9b23-00025b00a5c7"
        private val filter = "0000-1000-8000-00805f9b34fb"

        fun getUUIdDesc(uuid128Bit: String, defaultName: String = "Unknown Service"): String {
            val is16BitUuid = uuid128Bit.contains(filter, true)
            return if (is16BitUuid) {
                val uuid16Bit = uuid128Bit.substring(4, 8)
                uuids[uuid16Bit] ?: defaultName
            } else {
                when (uuid128Bit) {
                    SERVICE_OTA -> "BlueX Micro OTA Service"
                    CHARACTERISTIC_CTRL -> "BlueX Micro OTA CTRL"
                    CHARACTERISTIC_DATA -> "BlueX Micro OTA DATA"
                    SERVICE_BX_DEBUG -> "BlueX Micro DTM "
                    else -> defaultName
                }
            }
        }

        private var uuids = mapOf<String, String>(
            "0001" to "SDP",
            "0003" to "RFCOMM",
            "0005" to "TCS-BIN",
            "0007" to "ATT",
            "0008" to "OBEX",
            "000f" to "BNEP",
            "0010" to "UPNP",
            "0011" to "HIDP",
            "0012" to "Hardcopy Control Channel",
            "0014" to "Hardcopy Data Channel",
            "0016" to "Hardcopy Notification",
            "0017" to "AVCTP",
            "0019" to "AVDTP",
            "001b" to "CMTP",
            "001e" to "MCAP Control Channel",
            "001f" to "MCAP Data Channel",
            "0100" to "L2CAP",
            "1000" to "Service Discovery Server Service Class",
            "1001" to "Browse Group Descriptor Service Class",
            "1002" to "Public Browse Root",
            "1101" to "Serial Port",
            "1102" to "LAN Access Using PPP",
            "1103" to "Dialup Networking",
            "1104" to "IrMC Sync",
            "1105" to "OBEX Object Push",
            "1106" to "OBEX File Transfer",
            "1107" to "IrMC Sync Command",
            "1108" to "Headset",
            "1109" to "Cordless Telephony",
            "110a" to "Audio Source",
            "110b" to "Audio Sink",
            "110c" to "A/V Remote Control Target",
            "110d" to "Advanced Audio Distribution",
            "110e" to "A/V Remote Control",
            "110f" to "A/V Remote Control Controller",
            "1110" to "Intercom",
            "1111" to "Fax",
            "1112" to "Headset AG",
            "1113" to "WAP",
            "1114" to "WAP Client",
            "1115" to "PANU",
            "1116" to "NAP",
            "1117" to "GN",
            "1118" to "Direct Printing",
            "1119" to "Reference Printing",
            "111a" to "Basic Imaging Profile",
            "111b" to "Imaging Responder",
            "111c" to "Imaging Automatic Archive",
            "111d" to "Imaging Referenced Objects",
            "111e" to "Handsfree",
            "111f" to "Handsfree Audio Gateway",
            "1120" to "Direct Printing Refrence Objects Service",
            "1121" to "Reflected UI",
            "1122" to "Basic Printing",
            "1123" to "Printing Status",
            "1124" to "Human Interface Device Service",
            "1125" to "Hardcopy Cable Replacement",
            "1126" to "HCR Print",
            "1127" to "HCR Scan",
            "1128" to "Common ISDN Access",
            "112d" to "SIM Access",
            "112e" to "Phonebook Access Client",
            "112f" to "Phonebook Access Server",
            "1130" to "Phonebook Access",
            "1131" to "Headset HS",
            "1132" to "Message Access Server",
            "1133" to "Message Notification Server",
            "1134" to "Message Access Profile",
            "1135" to "GNSS",
            "1136" to "GNSS Server",
            "1137" to "3D Display",
            "1138" to "3D Glasses",
            "1139" to "3D Synchronization",
            "113a" to "MPS Profile",
            "113b" to "MPS Service",
            "1200" to "PnP Information",
            "1201" to "Generic Networking",
            "1202" to "Generic File Transfer",
            "1203" to "Generic Audio",
            "1204" to "Generic Telephony",
            "1205" to "UPNP Service",
            "1206" to "UPNP IP Service",
            "1300" to "UPNP IP PAN",
            "1301" to "UPNP IP LAP",
            "1302" to "UPNP IP L2CAP",
            "1303" to "Video Source",
            "1304" to "Video Sink",
            "1305" to "Video Distribution",
            "1400" to "HDP",
            "1401" to "HDP Source",
            "1402" to "HDP Sink",
            "1800" to "Generic Access Profile",
            "1801" to "Generic Attribute Profile",
            "1802" to "Immediate Alert",
            "1803" to "Link Loss",
            "1804" to "Tx Power",
            "1805" to "Current Time Service",
            "1806" to "Reference Time Update Service",
            "1807" to "Next DST Change Service",
            "1808" to "Glucose",
            "1809" to "Health Thermometer",
            "180a" to "Device Information",
            "180d" to "Heart Rate",
            "180e" to "Phone Alert Status Service",
            "180f" to "Battery Service",
            "1810" to "Blood Pressure",
            "1811" to "Alert Notification Service",
            "1812" to "Human Interface Device",
            "1813" to "Scan Parameters",
            "1814" to "Running Speed and Cadence",
            "1815" to "Automation IO",
            "1816" to "Cycling Speed and Cadence",
            "1818" to "Cycling Power",
            "1819" to "Location and Navigation",
            "181a" to "Environmental Sensing",
            "181b" to "Body Composition",
            "181c" to "User Data",
            "181d" to "Weight Scale",
            "181e" to "Bond Management",
            "181f" to "Continuous Glucose Monitoring",
            "1820" to "Internet Protocol Support",
            "1821" to "Indoor Positioning",
            "1822" to "Pulse Oximeter",
            "1823" to "HTTP Proxy",
            "1824" to "Transport Discovery",
            "1825" to "Object Transfer",
            "1827" to "Mesh Provisioning Service",
            "1828" to "Mesh Proxy Service",
            "2800" to "Primary Service",
            "2801" to "Secondary Service",
            "2802" to "Include",
            "2803" to "Characteristic",
            "2900" to "Characteristic Extended Properties",
            "2901" to "Characteristic User Description",
            "2902" to "Client Characteristic Configuration",
            "2903" to "Server Characteristic Configuration",
            "2904" to "Characteristic Format",
            "2905" to "Characteristic Aggregate Formate",
            "2906" to "Valid Range",
            "2907" to "External Report Reference",
            "2908" to "Report Reference",
            "2909" to "Number of Digitals",
            "290a" to "Value Trigger Setting",
            "290b" to "Environmental Sensing Configuration",
            "290c" to "Environmental Sensing Measurement",
            "290d" to "Environmental Sensing Trigger Setting",
            "290e" to "Time Trigger Setting",
            "2a00" to "Device Name",
            "2a01" to "Appearance",
            "2a02" to "Peripheral Privacy Flag",
            "2a03" to "Reconnection Address",
            "2a04" to "Peripheral Preferred Connection Parameters",
            "2a05" to "Service Changed",
            "2a06" to "Alert Level",
            "2a07" to "Tx Power Level",
            "2a08" to "Date Time",
            "2a09" to "Day of Week",
            "2a0a" to "Day Date Time",
            "2a0c" to "Exact Time 256",
            "2a0d" to "DST Offset",
            "2a0e" to "Time Zone",
            "2a0f" to "Local Time Information",
            "2a11" to "Time with DST",
            "2a12" to "Time Accuracy",
            "2a13" to "Time Source",
            "2a14" to "Reference Time Information",
            "2a16" to "Time Update Control Point",
            "2a17" to "Time Update State",
            "2a18" to "Glucose Measurement",
            "2a19" to "Battery Level",
            "2a1c" to "Temperature Measurement",
            "2a1d" to "Temperature Type",
            "2a1e" to "Intermediate Temperature",
            "2a21" to "Measurement Interval",
            "2a22" to "Boot Keyboard Input Report",
            "2a23" to "System ID",
            "2a24" to "Model Number String",
            "2a25" to "Serial Number String",
            "2a26" to "Firmware Revision String",
            "2a27" to "Hardware Revision String",
            "2a28" to "Software Revision String",
            "2a29" to "Manufacturer Name String",
            "2a2a" to "IEEE 11073-20601 Regulatory Cert. Data List",
            "2a2b" to "Current Time",
            "2a2c" to "Magnetic Declination",
            "2a31" to "Scan Refresh",
            "2a32" to "Boot Keyboard Output Report",
            "2a33" to "Boot Mouse Input Report",
            "2a34" to "Glucose Measurement Context",
            "2a35" to "Blood Pressure Measurement",
            "2a36" to "Intermediate Cuff Pressure",
            "2a37" to "Heart Rate Measurement",
            "2a38" to "Body Sensor Location",
            "2a39" to "Heart Rate Control Point",
            "2a3f" to "Alert Status",
            "2a40" to "Ringer Control Point",
            "2a41" to "Ringer Setting",
            "2a42" to "Alert Category ID Bit Mask",
            "2a43" to "Alert Category ID",
            "2a44" to "Alert Notification Control Point",
            "2a45" to "Unread Alert Status",
            "2a46" to "New Alert",
            "2a47" to "Supported New Alert Category",
            "2a48" to "Supported Unread Alert Category",
            "2a49" to "Blood Pressure Feature",
            "2a4a" to "HID Information",
            "2a4b" to "Report Map",
            "2a4c" to "HID Control Point",
            "2a4d" to "Report",
            "2a4e" to "Protocol Mode",
            "2a4f" to "Scan Interval Window",
            "2a50" to "PnP ID",
            "2a51" to "Glucose Feature",
            "2a52" to "Record Access Control Point",
            "2a53" to "RSC Measurement",
            "2a54" to "RSC Feature",
            "2a55" to "SC Control Point",
            "2a56" to "Digital",
            "2a58" to "Analog",
            "2a5a" to "Aggregate",
            "2a5b" to "CSC Measurement",
            "2a5c" to "CSC Feature",
            "2a5d" to "Sensor Location",
            "2a63" to "Cycling Power Measurement",
            "2a64" to "Cycling Power Vector",
            "2a65" to "Cycling Power Feature",
            "2a66" to "Cycling Power Control Point",
            "2a67" to "Location and Speed",
            "2a68" to "Navigation",
            "2a69" to "Position Quality",
            "2a6a" to "LN Feature",
            "2a6b" to "LN Control Point",
            "2a6c" to "Elevation",
            "2a6d" to "Pressure",
            "2a6e" to "Temperature",
            "2a6f" to "Humidity",
            "2a70" to "True Wind Speed",
            "2a71" to "True Wind Direction",
            "2a72" to "Apparent Wind Speed",
            "2a73" to "Apparent Wind Direction",
            "2a74" to "Gust Factor",
            "2a75" to "Pollen Concentration",
            "2a76" to "UV Index",
            "2a77" to "Irradiance",
            "2a78" to "Rainfall",
            "2a79" to "Wind Chill",
            "2a7a" to "Heat Index",
            "2a7b" to "Dew Point",
            "2a7c" to "Trend",
            "2a7d" to "Descriptor Value Changed",
            "2a7e" to "Aerobic Heart Rate Lower Limit",
            "2a7f" to "Aerobic Threshold",
            "2a80" to "Age",
            "2a81" to "Anaerobic Heart Rate Lower Limit",
            "2a82" to "Anaerobic Heart Rate Upper Limit",
            "2a83" to "Anaerobic Threshold",
            "2a84" to "Aerobic Heart Rate Upper Limit",
            "2a85" to "Date of Birth",
            "2a86" to "Date of Threshold Assessment",
            "2a87" to "Email Address",
            "2a88" to "Fat Burn Heart Rate Lower Limit",
            "2a89" to "Fat Burn Heart Rate Upper Limit",
            "2a8a" to "First Name",
            "2a8b" to "Five Zone Heart Rate Limits",
            "2a8c" to "Gender",
            "2a8d" to "Heart Rate Max",
            "2a8e" to "Height",
            "2a8f" to "Hip Circumference",
            "2a90" to "Last Name",
            "2a91" to "Maximum Recommended Heart Rate",
            "2a92" to "Resting Heart Rate",
            "2a93" to "Sport Type for Aerobic/Anaerobic Thresholds",
            "2a94" to "Three Zone Heart Rate Limits",
            "2a95" to "Two Zone Heart Rate Limit",
            "2a96" to "VO2 Max",
            "2a97" to "Waist Circumference",
            "2a98" to "Weight",
            "2a99" to "Database Change Increment",
            "2a9a" to "User Index",
            "2a9b" to "Body Composition Feature",
            "2a9c" to "Body Composition Measurement",
            "2a9d" to "Weight Measurement",
            "2a9e" to "Weight Scale Feature",
            "2a9f" to "User Control Point",
            "2aa0" to "Magnetic Flux Density - 2D",
            "2aa1" to "Magnetic Flux Density - 3D",
            "2aa2" to "Language",
            "2aa3" to "Barometric Pressure Trend",
            "2aa4" to "Bond Management Control Point",
            "2aa5" to "Bond Management Feature",
            "2aa6" to "Central Address Resolution",
            "2aa7" to "CGM Measurement",
            "2aa8" to "CGM Feature",
            "2aa9" to "CGM Status",
            "2aaa" to "CGM Session Start Time",
            "2aab" to "CGM Session Run Time",
            "2aac" to "CGM Specific Ops Control Point",
            "2aad" to "Indoor Positioning Configuration",
            "2aae" to "Latitude",
            "2aaf" to "Longitude",
            "2ab0" to "Local North Coordinate",
            "2ab1" to "Local East Coordinate",
            "2ab2" to "Floor Number",
            "2ab3" to "Altitude",
            "2ab4" to "Uncertainty",
            "2ab5" to "Location Name",
            "2ab6" to "URI",
            "2ab7" to "HTTP Headers",
            "2ab8" to "HTTP Status Code",
            "2ab9" to "HTTP Entity Body",
            "2aba" to "HTTP Control Point",
            "2abb" to "HTTPS Security",
            "2abc" to "TDS Control Point",
            "2abd" to "OTS Feature",
            "2abe" to "Object Name",
            "2abf" to "Object Type",
            "2ac0" to "Object Size",
            "2ac1" to "Object First-Created",
            "2ac2" to "Object Last-Modified",
            "2ac3" to "Object ID",
            "2ac4" to "Object Properties",
            "2ac5" to "Object Action Control Point",
            "2ac6" to "Object List Control Point",
            "2ac7" to "Object List Filter",
            "2ac8" to "Object Changed",
            "2ade" to "Mesh Proxy Data Out",
            "2add" to "Mesh Proxy Data In",

            "feff" to "GN Netcom",
            "fefe" to "GN ReSound A/S",
            "fefd" to "Gimbal, Inc.",
            "fefc" to "Gimbal, Inc.",
            "fefb" to "Stollmann E+V GmbH",
            "fefa" to "PayPal, Inc.",
            "fef9" to "PayPal, Inc.",
            "fef8" to "Aplix Corporation",
            "fef7" to "Aplix Corporation",
            "fef6" to "Wicentric, Inc.",
            "fef5" to "Dialog Semiconductor GmbH",
            "fef4" to "Google",
            "fef3" to "Google",
            "fef2" to "CSR",
            "fef1" to "CSR",
            "fef0" to "Intel",
            "feef" to "Polar Electro Oy",
            "feee" to "Polar Electro Oy",
            "feed" to "Tile, Inc.",
            "feec" to "Tile, Inc.",
            "feeb" to "Swirl Networks, Inc.",
            "feea" to "Swirl Networks, Inc.",
            "fee9" to "Quintic Corp.",
            "fee8" to "Quintic Corp.",
            "fee7" to "Tencent Holdings Limited",
            "fee6" to "Seed Labs, Inc.",
            "fee5" to "Nordic Semiconductor ASA",
            "fee4" to "Nordic Semiconductor ASA",
            "fee3" to "Anki, Inc.",
            "fee2" to "Anki, Inc.",
            "fee1" to "Anhui Huami Information Technology Co.",
            "fee0" to "Anhui Huami Information Technology Co.",
            "fedf" to "Design SHIFT",
            "fede" to "Coin, Inc.",
            "fedd" to "Jawbone",
            "fedc" to "Jawbone",
            "fedb" to "Perka, Inc.",
            "feda" to "ISSC Technologies Corporation",
            "fed9" to "Pebble Technology Corporation",
            "fed8" to "Google",
            "fed7" to "Broadcom Corporation",
            "fed6" to "Broadcom Corporation",
            "fed5" to "Plantronics Inc.",
            "fed4" to "Apple, Inc.",
            "fed3" to "Apple, Inc.",
            "fed2" to "Apple, Inc.",
            "fed1" to "Apple, Inc.",
            "fed0" to "Apple, Inc.",
            "fecf" to "Apple, Inc.",
            "fece" to "Apple, Inc.",
            "fecd" to "Apple, Inc.",
            "fecc" to "Apple, Inc.",
            "fecb" to "Apple, Inc.",
            "feca" to "Apple, Inc.",
            "fec9" to "Apple, Inc.",
            "fec8" to "Apple, Inc.",
            "fec7" to "Apple, Inc.",
            "fec6" to "Kocomojo, LLC",
            "fec5" to "Realtek Semiconductor Corp.",
            "fec4" to "PLUS Location Systems",
            "fec3" to "360fly, Inc.",
            "fec2" to "Blue Spark Technologies, Inc.",
            "fec1" to "KDDI Corporation",
            "fec0" to "KDDI Corporation",
            "febf" to "Nod, Inc.",
            "febe" to "Bose Corporation",
            "febd" to "Clover Network, Inc.",
            "febc" to "Dexcom, Inc.",
            "febb" to "adafruit industries",
            "feba" to "Tencent Holdings Limited",
            "feb9" to "LG Electronics",
            "feb8" to "Facebook, Inc.",
            "feb7" to "Facebook, Inc.",
            "feb6" to "Vencer Co, Ltd",
            "feb5" to "WiSilica Inc.",
            "feb4" to "WiSilica Inc.",
            "feb3" to "Taobao",
            "feb2" to "Microsoft Corporation",
            "feb1" to "Electronics Tomorrow Limited",
            "feb0" to "Nest Labs Inc.",
            "feaf" to "Nest Labs Inc.",
            "feae" to "Nokia Corporation",
            "fead" to "Nokia Corporation",
            "feac" to "Nokia Corporation",
            "feab" to "Nokia Corporation",
            "feaa" to "Google",
            "fea9" to "Savant Systems LLC",
            "fea8" to "Savant Systems LLC",
            "fea7" to "UTC Fire and Security",
            "fea6" to "GoPro, Inc.",
            "fea5" to "GoPro, Inc.",
            "fea4" to "Paxton Access Ltd",
            "fea3" to "ITT Industries",
            "fea2" to "Intrepid Control Systems, Inc.",
            "fea1" to "Intrepid Control Systems, Inc.",
            "fea0" to "Google",
            "fe9f" to "Google",
            "fe9e" to "Dialog Semiconductor B.V.",
            "fe9d" to "Mobiquity Networks Inc",
            "fe9c" to "GSI Laboratories, Inc.",
            "fe9b" to "Samsara Networks, Inc",
            "fe9a" to "Estimote",
            "fe99" to "Currant, Inc.",
            "fe98" to "Currant, Inc.",
            "fe97" to "Tesla Motor Inc.",
            "fe96" to "Tesla Motor Inc.",
            "fe95" to "Xiaomi Inc.",
            "fe94" to "OttoQ Inc.",
            "fe93" to "OttoQ Inc.",
            "fe92" to "Jarden Safety & Security",
            "fe91" to "Shanghai Imilab Technology Co.,Ltd",
            "fe90" to "JUMA",
            "fe8f" to "CSR",
            "fe8e" to "ARM Ltd",
            "fe8d" to "Interaxon Inc.",
            "fe8c" to "TRON Forum",
            "fe8b" to "Apple, Inc.",
            "fe8a" to "Apple, Inc.",
            "fe89" to "B&O Play A/S",
            "fe88" to "SALTO SYSTEMS S.L.",
            "fe87" to "Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )",
            "fe86" to "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )",
            "fe85" to "RF Digital Corp",
            "fe84" to "RF Digital Corp",
            "fe83" to "Blue Bite",
            "fe82" to "Medtronic Inc.",
            "fe81" to "Medtronic Inc.",
            "fe80" to "Doppler Lab",
            "fe7f" to "Doppler Lab",
            "fe7e" to "Awear Solutions Ltd",
            "fe7d" to "Aterica Health Inc.",
            "fe7c" to "Stollmann E+V GmbH",
            "fe7b" to "Orion Labs, Inc.",
            "fffe" to "Alliance for Wireless Power (A4WP)",
            "fffd" to "Fast IDentity Online Alliance (FIDO)",
            //特殊地
            "2600" to "BlueX Micro OTA Service",
            "7000" to "Ctrl",
            "7001" to "Data"
        )
    }
}